name: schedule_pipeline

on:
    schedule:
        - cron: '*/2 * * * *'

jobs:
    Hello-Twinkal:
        runs-on: ubuntu-latest
        steps:
            - name: Echo current time
              run: echo "The current time is $(date)"