name: schedule_pipeline

on:
    workflow_dispatch:
    schedule:
        - cron: '*/2 * * * *'

jobs:
    Hello_Twinkal:
        runs-on: ubuntu-latest
        steps:
            - name: Echo current time
              run: echo "The current time is $(date)"